# Generated by Django 5.2.6 on 2025-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="countlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
